- id: terraform-fmt
  name: Terraform fmt
  description: Rewrites all Terraform configuration files to a canonical format
  entry: pre-commit-hooks/terraform-fmt.sh
  language: script
  files: \.tf$
  exclude: \.terraform\/.*$
  require_serial: true

- id: sops-encrypt
  name: sops-encrypt
  description: Encrypt all the user-id's and passwords
  entry: pre-commit-hooks/sops-encrypt.sh
  language: script
  files: secrets.yaml
  require_serial: true